# Generated by Django 5.0.6 on 2024-07-05 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_document_email_count_downloadlog_emaillog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emaillog",
            old_name="recipient_email",
            new_name="recipient",
        ),
        migrations.RemoveField(
            model_name="document",
            name="email_count",
        ),
    ]
