# Generated by Django 5.0.6 on 2024-07-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_rename_recipient_email_emaillog_recipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="email_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
